twig:
    exception_controller: null # This is needed to fix the deprecation in Symfony 4.4
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
